documentation:
  - "docs/**"
  - "**/*.md"

github_actions:
  - ".github/*"
  - ".github/**/*"

terraform:
  - "components/terraform/**"
  - "components/terraform/**/*"
  - "**/*.tf"
  - "**/*.tfvars"
  - "stacks/**"

atmos:
  - "config/**"
