---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-json
        exclude: |
          (?x)^(
              .vscode/settings.json
          )$
      - id: check-yaml
      - id: sort-simple-yaml
      - id: check-symlinks
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace
      - id: detect-private-key

  - hooks:
      - id: avmfix
        name: autofix terraform
        entry: /usr/bin/env bash -c 'for dir in $(git diff --cached --name-only --diff-filter=ACM | grep ".tf$" | xargs -n1 dirname | sort -u); do avmfix --folder "$dir"; done'
        language: script
        files: \.tf$
    repo: local

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.92.2
    hooks:
      - id: terraform_fmt
      # avmfix validates and lints terraform better
      # - id: terraform_validate
      # - id: terraform_tflint
      - id: terraform_docs
        args:
          - --args=--config=.terraform-docs.yaml
          - --hook-config=--create-file-if-not-exist=false
          - --hook-config=--path-to-file=README.md
      - id: terraform_tfsec
        args:
          - -a --exclude-downloaded-modules -m HIGH --concise-output
