---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-json
      - id: check-yaml
      - id: sort-simple-yaml
      - id: check-symlinks
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace
      - id: detect-private-key
  # - repo: https://github.com/executablebooks/mdformat
  #   rev: 0.7.16
  #   hooks:
  #     - id: mdformat
  #       args:
  #         - --wrap=80
  #       exclude: README_TF\.md
  #       additional_dependencies:
  #         - mdformat-toc
  #         - mdformat-tables
  # - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
  #   rev: 0.2.3
  #   hooks:
  #     - id: yamlfmt
  #       args:
  #         - --mapping=2
  #         - --sequence=2
  #         - --offset=0
  #         - --width=80
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.80.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
      - id: terraform_docs
        args:
          - --args=--config=.terraform-docs.yaml
          - --hook-config=--create-file-if-not-exist=false
          - --hook-config=--path-to-file=README.md
      - id: terraform_tfsec
        args:
          - -a --exclude-downloaded-modules -m HIGH --concise-output
# - repo: local
#   hooks:
#   - id: terraform-docs-azure-components
#     name: terraform-docs-azure-components
#     entry: terraform-docs components/terraform/azure
#     language: system
#     pass_filenames: false
#     always_run: true

#   - id: terraform-docs-aws-components
#     name: terraform-docs-aws-components
#     entry: terraform-docs components/terraform/aws
#     language: system
#     pass_filenames: false
#     always_run: true

#   - id: terraform-docs-gcp-components
#     name: terraform-docs-gcp-components
#     entry: terraform-docs components/terraform/gcp
#     language: system
#     pass_filenames: false
#     always_run: true
