blank_issues_enabled: false

contact_links:
  - name: Slalom Build
    url: https://www.slalombuild.com/
    about: |-
      We're passionate about technology, compelled by its potential as we help create the digital products, experiences, and technology-driven organizations that drive true change.
