name: "💡 Feature Request"
description: "Create a request for a new feature."
title: "💡 [REQUEST] - replace-this-text-with-your-title"
labels: ["enhancement"]
body:
  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: Provide a brief explanation of the feature
      placeholder: Describe in a few lines your feature request
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      description: Urgent means this enhancement is required to resolve specific issues, Normal means this should be considered during regular planned work.
      multiple: false
      options:
        - Normal
        - Urgent
