name: Cache Test Workflow
on:
  push:
    branches:
      - tflint-cache-fix

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
    - name: Set current date as env variable
      run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
    - run: mkdir -p ~/my/folder
    - name: cache tflint plugins
      id: cache-plugins
      uses: actions/cache@v3
      with:
        path: ~/my/folder
        key: tflint-plugins-${{ env.NOW }}