name: Pull Request Workflow
on: [pull_request]

permissions:
  pull-requests: write
  id-token: write
  contents: read

env:
  TFLINT_PLUGINS: "aws azurerm google"

jobs:
  ci-terraform:
    uses: cloudposse/github-actions-workflows/.github/workflows/ci-terraform.yml@main
    with:
      suggestions: true
      filter-mode: nofilter